# This is a basic workflow that is manually triggered

name: Build and test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # copy rep
    # Runs a single command using the runners shell
      - name: Send greeting
        run: echo "Hello World!"
      - uses: actions/checkout@v3
      - name: install pyinstaller
        run: pip install pyinstaller
      - name: use program
        run: |
          pyinstaller --ex-3.py
          echo "OK"
      - name: Send main
        run: echo "Main flow is end!"
