
name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # Inputs the workflow accepts.


jobs:
 
  exe_builder:
   
    runs-on: ubuntu-latest

  
    steps:
    
      - name: Send greeting
        run: echo "Hello World!"
      - uses: actions/checkout@v3
      - name: install pyinstaller
        run: pip install pyinstaller
      - name: use pyinstaller
        run: |
          pyinstaller --onefile ex-3.py
          echo "OK"
      - name: Archive exe
        uses: actions/upload-artifact@v3
        with:
          name: Path to exe
          path: |
            ex-3.exe
            /home/runner/work/CreatePipeline/CreatePipeline/dist/ex-3.exe
      - name: Send end
        run: echo "Main flow is end!"
