
name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    


jobs:
 
  exe_builder:
   
    runs-on: windows-latest

  
    steps:
    
      - name: Send greeting
        run: echo "Hello World!"
      - uses: actions/checkout@v3
      - name: install pyinstaller
        run: pip install pyinstaller
      - name: use pyinstaller
        run: |
          pyinstaller --onefile ex-3.py
          echo "OK"
          dir
      - name: Path exe
        uses: actions/upload-artifact@v3
        with:
          name: Path to exe
          path: |
            ex-3.spec
      - name: go next
        run: |
          cd dist
          dir
      - name: Exe in
        uses: actions/upload-artifact@v3
        with:
          name: Exe
          path: |
            ex-3.exe
            D:\a\CreatePipeline\CreatePipeline\dist\ex-3.exe
            
  Upload_artifacts:
    needs: exe_builder
    runs-on: ubuntu-latest
    
    steps:
      - name: Add artifact
        uses: actions/download-artifact@v3
      - name: Check
        run: ls
      - name: upload to google drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.CREDENTIALS }}
          filename: Exe/dist/*
          folderId: ${{ secrets.FOLDERID }}
          overwrite: "true"
  Refactor_code:
    needs: Upload_artifacts
    runs-on: ubuntu-latest
    
    steps:
      - name: Check code
        uses: actions/checkout@v3
      - name: Install styleguide
        run: pip install wemake-python-styleguide
      - name: use styleguide
        run: |
          flake8 ex-3.py
          echo "OK"
      - name: Send end
        run: echo "Main flow is end!"
